version: "3.7"

services:
  api:
    build: ./api/
    restart: always
    ports:
      - 8080:3000
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432 
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: api-backend
      POSTGRES_DB: plzhireus
    security_opt:
      - seccomp:unconfined
