version: "3.7"

services:
  api:
    build: ./api/
    restart: always
    ports:
      - 8080:3000
    depends_on: 
      - db

  db:
    image: mysql
    volumes:
      - ./docker-volumes/db:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: "api-backend"
      MYSQL_PASSWORD: "example"
      MYSQL_DATABASE: "plzhireus"
    security_opt:
      - seccomp:unconfined